FROM node:14

WORKDIR /apps/web

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build


WORKDIR /apps/api

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

RUN yarn build


EXPOSE 3000

EXPOSE $PORT

CMD ["yarn", "start:prod"]