version: "3.8"
services:
  postgres:
    image: postgres:13
    container_name: postgresprisma
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ./apps/backend/.env.development
    volumes:
      - postgres:/var/lib/postgresql/data
  nestjs:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    env_file:
      - ./apps/backend/.env.development
    ports:
      - 3005:3000
    volumes:
      - ./apps/backend/:/app
      - /app/node_modules
volumes:
  postgres:
    name: nest-prisma-docker-db
