FROM node:14

WORKDIR /apps/web

COPY apps/web/package.json ./
COPY apps/web/yarn.lock ./

RUN yarn install

COPY apps/web .

RUN yarn build


WORKDIR /apps/api

COPY apps/api/package.json ./
COPY apps/api/yarn.lock ./

RUN yarn install

COPY apps/api .

RUN yarn build


EXPOSE 3000

EXPOSE $PORT

CMD ["yarn", "start:prod"]