version: '3.8'
services:
  adminer:
    image: adminer
    depends_on:
      - postgres
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: postgres:13
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    command: npm run start:dev
    depends_on:
      - postgres
    links:
      - postgres:postgres
    env_file:
      - .env
    ports:
      - '3000:3000'
