version: '3.8'
services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  postgres:
    image: postgres:13
    restart: always
    ports:
      - '35000:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
