name: Restore db from dump

defaults:
  run:
    working-directory: ./apps/api

on: workflow_dispatch

jobs:
  restore:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Run restoring from file
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku pg:psql DATABASE_URL  -a ${{ secrets.HEROKU_APP_NAME }}  -f ./src/database/dump/seed.sql
