name: deploy

on: workflow_dispatch

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      deployment_id: ${{ steps.setup.outputs.deployment_id }}
    steps:
      - id: setup
        uses: chrnorm/deployment-action@releases/v1
        name: Create GitHub deployment
        with:
          token: "${{ github.token }}"
          target_url: https://still-basin-01257.herokuapp.com/
          initial_status: "pending"
          environment: Production

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v3

      - name: Login to Heroku Container registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Remove docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker rmi $(docker images -a -q)

      - name: Build docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker image build . -f Dockerfile.prod --tag registry.heroku.com/still-basin-01257/web

      - name: Push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker push registry.heroku.com/still-basin-01257/web

      - name: Remove docker image
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: docker rmi $(docker images -a -q)

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a still-basin-01257 web

      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://still-basin-01257.herokuapp.com/
          state: "success"
          deployment_id: ${{ needs.setup.outputs.deployment_id }}

      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@releases/v1
        with:
          token: "${{ github.token }}"
          target_url: https://still-basin-01257.herokuapp.com/
          state: "failure"
          deployment_id: ${{ needs.setup.outputs.deployment_id }}
